# Lenguaje del proyecto en el que usamos integraci贸n continua
language: node_js # language runtime

# Versi贸n del lenguaje 
node_js:
  - 10.16.2

build:
  ci: # Construcci贸n para CI
    - npm install         # para instalar dependencias
    - npm run test        # para ejecutar los test unitarios
    - npm run coveralls   # para comprobar cobertura de c贸digo