# Lenguaje del proyecto en el que usamos integración continua
language: node_js

# Versiones del lenguaje 
node_js:
  - 10.16.2    # probamos con dos versiones
  - 12.10.0

before_install:
  - npm install gulp  # instalación herramienta de construcción

# Construcción para CI
install:
  - npm install         # instalamos dependencias
#  - gulp install         # instalamos dependencias

script:
  - gulp test            # ejecución de tests unitarios y funcionales

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage