#!/bin/bash

docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

docker build -t pramartinez/vptournaments .
docker tag vptournaments pramartinez/vptournaments:latest

docker push pramartinez/vptournaments

