# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "VPT-vm"
  # Especificamos el dummy box, el cual nos proporcionará una base para nuestra máquina.
  config.vm.box_url = 'https://github.com/msopentech/vagrant-azure/raw/master/dummy.box'

  # Clave privada del par usado para conectarse a la VM
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider "azure" do |vm, override|
    vm.tenant_id="c7a95d24-50ff-4804-ad9a-e4cba81ad10b"
    vm.client_id="518f9d83-efda-4975-a32c-453c817082cc"
    vm.subscription_id="0742ef1e-9172-4d37-a4e0-9ff6ab96659e"
    vm.client_secret="c9399600-4aa2-42df-a04f-b45befa3522c"

    vm.vm_name = "azure-vm"
    vm.resource_group_name= "RGN-vm"
    vm.vm_image_urn = "Canonical:UbuntuServer:18.04-LTS:latest"
    vm.vm_size = "Standard_B1s"
    #vm.tcp_endpoints = ENV['PORT']
    vm.tcp_endpoints = "80"
    vm.location = "westeurope"
    
  end

# Enable provisioning with a shell script. Additional provisioners such as
# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
# documentation for more information about their specific syntax and use.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/myplaybook.yml"
  end
end
